spring:
  application:
    name: Financial Service Application

  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev, faker

  springdoc:
    api-docs:
      enabled: false

  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:8080/realms/jhipster
        registration:
          oidc:
            client-id: jhipster-app
            client-secret: web_app
            scope: openid, profile, email, offline_access # last one for refresh tokens
      resourceserver:
        jwt:
          principal-claim-name: preferred_username

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  clientApp:
    name: 'financialServiceApplicationApp'
  # By default CORS is disabled. Uncomment to enable.
  # cors:
  #   allowed-origins: "http://localhost:8100,http://localhost:9000"
  #   allowed-methods: "*"
  #   allowed-headers: "*"
  #   exposed-headers: "Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params"
  #   allow-credentials: true
  #   max-age: 1800
  mail:
    from: financialServiceApplication@localhost
  api-docs:
    default-include-pattern: /api/**
    management-include-pattern: /management/**
    title: Financial Service Application API
    description: Financial Service Application API documentation
    version: 0.0.1
    terms-of-service-url:
    contact-name:
    contact-url:
    contact-email:
    license: unlicensed
    license-url:
  security:
    content-security-policy: "default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:"
    oauth2:
      audience:
        - account
        - api://default
